project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: EDS 232 - Machine Learning for Environmental Science
  page-footer: 
    left: "This work is licensed under [CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License](https://creativecommons.org/licenses/by-nc/4.0/)" 
    right: This website is built with [Quarto](https://quarto.org/) and [GitHub pages](https://github.com/MEDS-eds-220/MEDS-eds-220-course).
  
  announcement: 
    icon: hammer
    dismissable: true
    content: "This wesbite is under construction."
    type: primary
    position: below-navbar
    
  navbar:
    right:
      - text: home
        href: index.qmd
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

link-external-newwindow: True